id: A59395384
title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
  Deities of the Self-Liberated Wisdom Mind'
type: translation
pechas:
- I1F086150
- IBD83F773
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:46:50.816664
  last_modified_at: 2023-01-04 12:46:50.816686
  collections:
  - Karma Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I1F086150/6E5E: 43DB
  IBD83F773/9A40: 43DB
